### ISSUE TITLE
appointed controls don't work in vrchat

### ISSUE THREAD

**Issue by mar325** [elvissteinjr/DesktopPlus#11]
hey elvis
i have noticed that my controls that is set works in steam vrhome (actions button 1,2,3)
but when i start vrchat they dont work.
maby they dont work because vrchat already uses te same stick and puller only is set the thumbstick controls on up en down and in vrchat you only use left and right on you right thumbstick
hopefully we can find a solution
many thanks
mar325

**Comment by elvissteinjr** [comment]
Sorry, but I can't reproduce your issue. Bound actions work in VRChat on my end.
You'll have to go into more detail here. In particular, it would be useful to know what the action you're trying to bind is doing.

**Comment by mar325** [comment]
i fixed it i needed to bound the enable floating overlay interaction
now i can click on the floating overlay to select te right page and use joystick up and down to go up and down
i have noticed that you dont have the action key code scroll panel so that when i hold my joystick up it will scrolls up or down
hopefully you can do something with this
many thanks i love you app
greetings mar325
