### ISSUE TITLE
No Desktop 2 option for capturing

### ISSUE THREAD

**Issue by VsevolodGolovanov** [elvissteinjr/DesktopPlus#14]
I used to be able to capture Desktop 2, but now for some reason it only has Deskop 1, my main desktop:
![image](https://user-images.githubusercontent.com/8070317/105073050-94ec2e80-5a97-11eb-96cd-de6ee68f0752.png)

This is using `DesktopPlusUI.exe -DesktopMode`.

It used to work and stopped working on a single pre Steam version, 2.3.1 I think.
I updated to the Steam version - it's 2.3.3 now, but nothing changed - can't see Desktop 2.

I'm using
![image](https://user-images.githubusercontent.com/8070317/105073368-0d52ef80-5a98-11eb-8f97-0c3bef2eb8b0.png)

My monitor layout is
![image](https://user-images.githubusercontent.com/8070317/105073425-1cd23880-5a98-11eb-9b43-543bbd5e8cba.png)
My desired Desktop 2 is marked as 4 here.

I switch between monitor configurations - I enable 2-3 and disable 4 and vice versa. Never while running VR though. I always run VR in this configuration, when there's only 1 and 4.
Disabled as in this in Windows monitor settings:
![image](https://user-images.githubusercontent.com/8070317/105073733-7cc8df00-5a98-11eb-9d30-482efd4fef4f.png)
And enabled monitor 4 looks like:
![image](https://user-images.githubusercontent.com/8070317/105073760-881c0a80-5a98-11eb-9cb8-808d898ad768.png)

All monitors and the headset are on the same GPU.

**Comment by VsevolodGolovanov** [comment]
Offtop: tried using Graphics capture instead on MPC-HC, and it works, but flickers every now and then. Desktop Duplication seems to work better.

**Comment by elvissteinjr** [comment]
What VR headset are you using? If it's a Windows Mixed Reality one, check if changing the "Ignore WMR Virtual Desktops" setting helps. 
Desktop enumeration has changed a bit in the last beta build that just came out as well. I'd recommend trying that one out. You can either switch to the beta branch on Steam or grab the latest build off of GitHub.
I'm not sure why it'd happen if above doesn't apply to you though. In your build, Desktop+ just asks Windows for the amount of the connected monitors and lists that many desktops.

Regarding things not capturing well with Graphics Capture, I know there are a few window setups that don't work well (especially stuff using multiple windows internally), but it's not really in my power to fix unfortunately. Desktop+ receives the captured frames as it gets them and forwards them to SteamVR as they are.
I don't have MPC-HC installed (more of a mpv guy myself) so I can't check right now, but if you want you could check with another app supporting Graphics Capture like OBS Studio and see if you get similar behavior.

**Comment by VsevolodGolovanov** [comment]
Ya, it's Odyssey+. Thanks for the tips, I'll check those out.

**Comment by VsevolodGolovanov** [comment]
Desktop 2 appeared and seems to be capturing fine fine with 2.3.5 Beta.
