### ISSUE TITLE
Elevated Mode not working

### ISSUE THREAD

**Issue by Valgorythm** [elvissteinjr/DesktopPlus#16]
Hi,
I ran the .bat file, the scheduled task was created properly and it runs fine when I click "Enable Elevated Mode" in the Desktop+ overlay Misc tab.
But then, when I try to launch a program that pops a UAC confirmation prompt, on Desktop+ I only see a black screen, and I can't interact with the prompt with the virtual keyboard, or with Actions (Left Arrow + Enter for example).

**Comment by elvissteinjr** [comment]
You will have to disable the dimmed secure desktop for the UAC prompt. Desktop+ can't mirror or interact with it regardless of running elevated or not.
This will not disable UAC in itself or be a lot less secure in my opinion. Applications running as administrator will be able to interact with the prompt now... but they don't need to do that to do any harm in the first place if they wanted to.

**Comment by Valgorythm** [comment]
Thanks for the quick reply.
I simply didn't know that the dimmed secure desktop could be disabled.
I'm closing the issue then, thank you for your time, and for your amazing work on Desktop+
