### ISSUE TITLE
WMRIgnoreVScreens options should be ignored when a WMR headset is not connected

### ISSUE THREAD

**Issue by heclak** [elvissteinjr/DesktopPlus#2]
If the following settings are present in the config.ini files, the additional monitors are removed regardless if a WMR headset is currently used.

```
WMRIgnoreVScreensSelection=1
WMRIgnoreVScreensCombinedDesktop=1
```

I found this out because I a WMR (Odyssey+) and an Oculus Quest. Switching between both of them causes issues with the display of the monitors. After turning on both options in the WMR headset, the app functions correctly with the WMR headset. But when switching to the Oculus headset (I assume any WMR headset would have the same bug), only my first display appears even though I have two displays. I assume the -3 displays option is still doing its job. But since the options in the settings menu only appear when a WMR headset is used, I can't go the settings menu to deactivated them without editing the ini file manually or reconnecting my WMR headset to switch the options. 

My suggestion is to only remove the last three v-displays only if the currently used HMD is a WMR headset, regardless of the ini settings. But if a WMR headset is used, check and apply the options in the ini file.

**Comment by elvissteinjr** [comment]
Just ignoring these settings when they don't apply makes more sense indeed. Should be fixed now.
Thank you.
