### ISSUE TITLE
Got a distorted view when overlay was attached to HMD

### ISSUE THREAD

**Issue by zmz125000** [elvissteinjr/DesktopPlus#23]
Got a curved view (distortion) when overlay was attached to HMD

look forward: Overlay is rectangle.
look up or down: Overlay is convex quadrilateral.

I use OpenTrack and _attached Overlay to HMD_ to make head motion supported games work with HMD, with corrected FOV settings it makes standard games play like VR games without 3D effect. In DesktopPlus the Overlay was curved to a convex quadrilateral and I got a distorted view. The curvature setting has no effect on this behavior.

I tried OVR Toolkit's floating overlay and it kept a rectangle shape.

![Screenshot (12)](https://user-images.githubusercontent.com/11844731/117093425-7e8e8800-ad93-11eb-825b-b53392a25f98.jpg)
![Screenshot (11)](https://user-images.githubusercontent.com/11844731/117093429-7fbfb500-ad93-11eb-82a4-1c23df8babc9.jpg)
![Untitled](https://user-images.githubusercontent.com/11844731/117094281-f6f64880-ad95-11eb-92c9-c457d2a952ae.jpg)

**Comment by elvissteinjr** [comment]
Are you sure you were changing the settings on the right overlay? On your screenshot the curvature slider doesn't appear to be all to the left.
The effect you're describing happens with curved overlays depending on their orientation, but that's a quirk of SteamVR, so not much I can do there. Flat overlays should not have this at all, however.

**Comment by zmz125000** [comment]
It appears that I selected the wrong overlay in settings.
