### ISSUE TITLE
Overlays always scroll up when input is enabled

### ISSUE THREAD

**Issue by SilentMrDave** [elvissteinjr/DesktopPlus#24]
Anytime I point to any of my overlays that have input enabled they scroll upwards. I'm thinking this might have something to do with my touchpads as I'm on Mixed Reality. Is there a touchpad dead zone setting anywhere that I'm missing or an option to disable scrolling? Any help would be appreciated.

**Comment by elvissteinjr** [comment]
Scrolling events come straight from SteamVR, so Desktop+ is not in control how those are generated. Generally scrolling can happen from any controller as long as one of them points at the overlay. In case of WMR probably from touchpad and sticks.

Scrolling bindings are configured in the input bindings for the VR Dashboard. This actually came up recently over on the [Steam forums](https://steamcommunity.com/app/1494460/discussions/3/3132792921905172652/). There are deadzone settings for those bindings but they don't show up in the UI, I believe. 
You can try out the steps OP did on the forum thread or use their published bindings. Didn't try them myself, so no guarantees, but they seemed to be happy with the result.

As for deactivating scrolling, there's currently no option for that, save for removing scrolling from the VR Dashboard bindings... which affects all overlays from any app. I'll consider adding that at least as a hidden setting if it keeps coming up, though.

**Comment by SilentMrDave** [comment]
Configuring bindings to disable the touchpad did the trick. I do wish there was a way to calibrate the touchpad but I know that is on Steam or Windows' end. Thanks for the advice.
