### ISSUE TITLE
Feature Request: Show headset battery level

### ISSUE THREAD

**Issue by sctanf** [elvissteinjr/DesktopPlus#26]
Probably only a few headsets support this. I can see there is a battery meter/charge indicator for my headset at the top of the SteamVR dashboard, it would be nice to see the percentage in Desktop+ stats screen as well.

**Comment by elvissteinjr** [comment]
Sure thing. I've just pushed code to show HMD battery level on the Performance Monitor if SteamVR reports the device to support that.
Can't test it though, so before I release a non-working beta build, I've attached an updated binary of the UI executable so you can check it out without building it yourself.

[DesktopPlusUI-HMD-Battery-Test.zip](https://github.com/elvissteinjr/DesktopPlus/files/6837510/DesktopPlusUI-HMD-Battery-Test.zip)

**Comment by sctanf** [comment]
Thanks! Looks like it shows up correctly, nice.
![Screenshot 2021-07-19 024606](https://user-images.githubusercontent.com/36978460/126122428-9978f0a5-87ec-4f61-a599-5553176c90a9.png)
