### ISSUE TITLE
Feature Request: Gaze Fade %

### ISSUE THREAD

**Issue by davidc1701** [elvissteinjr/DesktopPlus#28]
Currently, the Gaze Fade option for overlay windows will drop the opacity to 0% when not looking at the overlay.

This request is for a setting to change that number.

For example, when I am looking at my screen, I would like it to be at 100% opacity, but when I am not directly looking at it, I would like it to be 50% opacity, so it would be helpful to have a setting to adjust what the opacity becomes when not looking directly at the overlay, which could be set at anything from 0-100% (which would also cover niche cases when you want it to be less opaque when looking directly at the screen than when not.)

**Comment by elvissteinjr** [comment]
Target opacity setting does make sense, so I'll add that when I have the time, sure. Inverted behavior when target is higher than the overlay's opacity setting could go along with it.

**Comment by elvissteinjr** [comment]
This is now implemented in code. Sorry for the delay.
As for a binary release containing this, I wanted the next one to be a stable release as it's been a while. I still need a little more time there, however.

**Comment by elvissteinjr** [comment]
This is now available in the v2.6 build.
