### ISSUE TITLE
Feature request: Automatically turn off Shift key after single press

### ISSUE THREAD

**Issue by matejdro** [elvissteinjr/DesktopPlus#32]
Currently, shift key stays active after typing a letter. This is a bit counterintuitive compared to how actual shift works (usually you only press shift once. If you need multiple uppercase letters, you can use caps lock, which should be sticky).

**Comment by elvissteinjr** [comment]
Unless I'm missing something, that should already be covered by the "Sticky Modifier Keys" setting. I already noticed some inconsistencies with that setting in regards to toggling multiple modifiers at once in the current build, but the basic shift -> key functionality should be fine right now.

**Comment by matejdro** [comment]
Duh, I'm an idiot and I've missed this option. Thanks!
