### ISSUE TITLE
Feature request: Keyboard Key Popups

### ISSUE THREAD

**Issue by matejdro** [elvissteinjr/DesktopPlus#33]
Coming from the mobile word, keyboards have a nice feedback feature where typed letter pops up after you type it:

![image](https://user-images.githubusercontent.com/507922/143033632-f9cca4c6-abf4-4678-91e2-39e504c0ec07.png)

Since keyboard is usually below the screen, I must look down and cannot see what I'm typing and if I'm making any typos. It would be nice to get that small form of feedback so you are sure which key has been pressed.

**Comment by elvissteinjr** [comment]
Not really sold on this one to be honest. This kind of hint makes sense on mobile where the finger covers the actual key entirely, but in VR the pointer doesn't really obscure it all that much imo. 
Feels like it would just be a highlight of the same thing you can already see (and you can't slip off keys either as long as they're pressed).

**Comment by matejdro** [comment]
Huh yeah, you are right. I've been thinking on how to improve my VR keyboard accuracy and this has been the only idea I had. But now that you've mentioned, it is not really that helpful. Will try to think of a better way.
