### ISSUE TITLE
Might be dumb

### ISSUE THREAD

**Issue by Renalic** [elvissteinjr/DesktopPlus#4]
I may be an idiot, but i've searched through the file two or three times now and cant seem to find the Desktop+.exe ascribed in the readme. Could someone be so kind as to provide extra help?

**Comment by elvissteinjr** [comment]
Are you sure you haven't accidentally downloaded the source code archive? That's usually not the one you want unless you know what you're doing.

For the current version 2.2 release, download [this archive](https://github.com/elvissteinjr/DesktopPlus/releases/download/v2.2/DesktopPlus-2.2.zip).

**Comment by elvissteinjr** [comment]
Closing this to clean up as I assume this solved your issue back then. If you still have trouble with anything feel free to open a new issue.
