### ISSUE TITLE
[Help Requested] Main Desktop+ Window not scaling properly

### ISSUE THREAD

**Issue by ZenithRev** [elvissteinjr/DesktopPlus#47]
User is on windows 10, using SteamVR and an Index.

I normally run a desktop resolution of 2560x1440, and Desktop+ worked fine with it until I recently played a game that forced 1920x1080. Now, even after a reboot and resetting to 2560x1440, my main window for Desktop+, the one appearing above my SteamVR menus while in VR, acts like I am still on 1920x1080. 

Oddly, my window capture displays are fine. JUST the main window has this issue. How can I fix this? Any help would be appreciated!

**Comment by elvissteinjr** [comment]
Have you tried resetting the cropping values? Desktop Duplication overlays are all cropped from the combined desktop texture. Resolution/arrangement changes should be detected if they happen during runtime and adapted for, but not if they happen between launches.
Switching around desktops with the buttons should also fix it. If we don't have any other issue at hand, that is.

The in-development NewUI branch handles this a bit better by hiding that implementation detail (max crop is resolution selected desktop) and offering a straight crop toggle on top of that. For the stable branch it is what it is right now, however.
Hope that helps.

**Comment by ZenithRev** [comment]
Thank you for the quick reply! A question... where do I adjust that for the main window? I found cropping for the extra displays for each app, but not my main window. I only have one desktop, but could try making another if needed.

**Comment by elvissteinjr** [comment]
The main overlay would be the one that says "[Dashboard] *Name*" in the overlay selector. Always the first one in the list. Cropping can be adjusted in the [Capture tab](https://github.com/elvissteinjr/DesktopPlus/blob/master/docs/user_guide.md#capture).

Unless we're both talking about different things somehow (doesn't sound like you have trouble managing additional overlays after all). Cropping should work the same for all overlays.

**Comment by ZenithRev** [comment]
Close enough! I was able to fixthis by toggling to the dashboard's sample profile, then back to my real one. This has fixed most of my problem, and I can probably fix the rest on my own. Thanks for the help!

Closing this as RESOLVED.
