### ISSUE TITLE
Minor issue: Gaze fade "sticks" when entering Drag mode

### ISSUE THREAD

**Issue by Identifier** [elvissteinjr/DesktopPlus#57]
This happens in NewUI (I haven't tested it in the main branch):

* Create an overlay and configure it's gaze fade to fade out when you look away from it.
* Enable 'drag mode' (e.g. by clicking the drag mode button in a floating UI of an overlay)
* Notice that the transparency of the overlay no longer fades in or out when you look towards/away from it.
* Disable 'drag mode' (e.g. by clicking the button again)
* Fade in/out starts working again.

Not sure if it's a bug or a feature.  It was actually kind of cool being able to make the overlay stuck in a semi-transparent state when enabling drag mode, so that I could precisely position it when it's stuck slightly transparent.

**Comment by elvissteinjr** [comment]
I had this fixed by the time NewUI Preview 12 was released, but forgot to respond here, oops.
Thanks for the report as usual.
