### ISSUE TITLE
When i re-enter desktop+ all the screen i set-up rotate toward the floor

### ISSUE THREAD

**Issue by cnnhean** [elvissteinjr/DesktopPlus#61]
As the title say, i organize my multiple screens, position based on dashboard, when i re-enter the software, after few times(or a steamvr reset it seems), all the screen other then the center screen lose orientation and rotate about 45 degrees downwards the floor and move a bit farther from me.

This oriantation now stays, when i restart, it doesn't keep changing, unless i try to fix it, and they revert back to this oriantation. 

I saved each screen into a profile, but it when i load the profile, it stays with the same bug, so it's like in my case desktop+ gets wrong/different dashboard values when i restart vr or it saves the set-up with different dashboard position values
..
Either way it renders it impossible to use the software..

I use the Pimax Crystal, so that may be related to the issue.

I've also posted this on steam discussions bugs sub forum.

If the dashboard approximation gets it wrong/different sometimes, it would be very usful to be able to manually offset the approximation so that all the work of setting up the monitors wouldn't go to waste...

**Comment by elvissteinjr** [comment]
Hi, I responded to you on the Steam forums. I had decided put an experimental fix for this on the beta branch over there before pushing something out on main that doesn't work for everyone.

Can you see if it works for you?

**Comment by cnnhean** [comment]
It's really amazing that you already placed an expirimental fix, i will try to test it as soon as i have that free time, hopefully today

**Comment by cnnhean** [comment]
Sorry for the long delay with my response. 

Yes it seems to have fixed it, now i will use it delay and will see if it occur again, i will update here if it does.

Thank you for the fast fix !

**Comment by cnnhean** [comment]
I believe this is completely fix after testing it for a while, 
I'm really happy with it. 
Thank you!
