### ISSUE TITLE
Multiple pointers on keyboard in dashboard (Steam VR 2.0)

### ISSUE THREAD

**Issue by matejdro** [elvissteinjr/DesktopPlus#67]
I'm wondering if it is possible to introduce multiple pointers to the keyboard in the dashboard? Steam VR 2.0's keyboard does it, so maybe it is more possible now than it used to be?

**Comment by elvissteinjr** [comment]
Yes, that's a pending addition for the next NewUI build. 
The OpenVR API update that allows for this only came out a couple of days ago, though (later than the SteamVR 2 stable release).
Had a hacky solution working during the SteamVR Beta (the new overlay flags were usable if you knew their value, not much else), but now I'm likely better off scrapping that and use the full extent of the API instead.
